### ISSUE TITLE
UnicodeDecodeError if local args contains byte string

### ISSUE THREAD

**Issue by SirScott** [MindscapeHQ/raygun4py#18]
With the python 2 implementation, I'm getting a `UnicodeDecodeError` when trying to use `send_exception`.  Looks like the `jsonpickle.encode()` is blowing up, specifically when trying to encode the `raygunMessage['details']['error'].stackTrace` list.  One of the stackTrace items has a `localVariables` dict with a key `verification` that contains the following value:  `\x8d\x80\x92uK!M\xed\x16u3\x0b\xcc\xb1r1N\xdfs\x13,>\x01\x87\xae\xd0E\xe8\x02\x05\xd0d\xaa\xbd\xc9wc}\x1b\xbd\x06\xf8R3\xb4\xf3_F\x1b\xac}\xba\x11gul%v9\xf8\x0cp\x03\t`

If the config option `transmitLocalVariables` is set to `False`, the issue goes away, as you might expect.  However, I'd really like to be able to send all local vars!

**Comment by fundead** [comment]
Hi Scott,

Thanks heaps for finding this one and the comprehensive report. I've managed to repro this locally and am working on a fix, will look at getting this out in a point release in the very near term.

Regards,

Callum Gavin
Mindscape Limited

**Comment by fundead** [comment]
So as it turns out, this appeared to most likely be a bug/unimplemented feature in jsonpickle. With the previous jsonpickle 0.7.0 dep, adding a unicode environment variable with a high code point such as ☼ causes the test suite to throw the `UnicodeDecodeError: 'utf8' codec can't decode byte 0xa4`. I also previous repro'd your bytestring example on Windows where it threw the same error.

These look to be fixed by bumping jsonpickle to the latest v0.9.2, most likely due to including the fix at https://github.com/jsonpickle/jsonpickle/pull/110. Seems to be passing on travis, if you want to pull down the PR and run `python setup.py install` you would be able to confirm the fix, however as this appears to resolve an outstanding bug I'll look at getting this released later today if there's no objections.

**Comment by SirScott** [comment]
Hi Callum,

Thanks a lot for taking a look into it.  I won't be able to apply the PR until tomorrow, but glancing over it, it certainly seems promising.  So feel free to go ahead and merge in it and cut the release.  Should I run into any troubles with v3.0.2, I'll just submit a new issue!

Thanks again!

**Comment by SirScott** [comment]
OK, I did manage to get this pulled down and applied.  All looks good!

**Comment by fundead** [comment]
Great to hear! Releasing this now as v3.0.2.
