### ISSUE TITLE
http request timeout

### ISSUE THREAD

**Issue by diwu1989** [MindscapeHQ/raygun4py#25]
can you enable timeout to be set? so that the request won't hang?

**Comment by fundead** [comment]
Are you referring to the HTTP POST request that occurs when you call `send_exception()`? In what circumstance does it hang, due to network layer issues?

This provider is not due for a revision immediately but note that we do accept pull requests, and this can speed up getting a fix tested and released.

Regards,

Callum Gavin
Raygun Limited

**Comment by diwu1989** [comment]
Yes, if the network layer is bad, for example, a bad dns, or any other random issues on your end, then the client can be blocked for a long time

**Comment by fundead** [comment]
Ah yes, that makes sense and is worth resolving. I should be able to take a look at this provider in the next couple of weeks barring a PR appearing.

**Comment by fundead** [comment]
This issue has now been resolved in the latest release above, which has a configurable timeout with a default of 10s.
