### ISSUE TITLE
What is the purpose of deleting the exception traceback

### ISSUE THREAD

**Issue by diwu1989** [MindscapeHQ/raygun4py#26]
What is the point of these lines:
https://github.com/MindscapeHQ/raygun4py/blob/master/python2/raygun4py/raygunprovider.py#L78-L81

The line that's weird is:
```py
try:
  delete ...
except Exception e:
  raise
```
isnt that equivalent to just straight up
```py
delete ...
```
without the try except?
and why do you even need to delete those local variables, they'll get garbage collected at the interpreter's discretion

**Comment by fundead** [comment]
As it turns out they will not in fact be GC'd, as a function that is handling an exception, if the traceback is assigned to a local variable, will result in a circular reference, This is noted in the official documentation at https://docs.python.org/2/library/sys.html#sys.exc_info, in the Warning note, and the above code is the recommended approach. Similar implementations exist in other libraries.
